"""testing migrations

Revision ID: 3c1df68ffaeb
Revises: 8e359b67948a
Create Date: 2021-05-07 19:39:39.537875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1df68ffaeb'
down_revision = '8e359b67948a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('test', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'test')
    # ### end Alembic commands ###
